apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shopmicro
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: backend
        image: timiajiboye/shopmicro-backend:latest
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_USER
          value: "user_admin"  # Must match postgres.yaml
        - name: DB_NAME
          value: "shopmicro"   # Must match postgres.yaml
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shopmicro-secrets
              key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shopmicro
spec:
  type: LoadBalancer # <--- THIS IS CRITICAL for public access
  selector: { app: backend }
  ports:
  - port: 80           # What the browser uses (Standard HTTP)
    targetPort: 8080    # What your Go/Python/Node app listens on