apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shopmicro
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: backend
        image: timiajiboye/shopmicro-backend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shopmicro
spec:
  type: LoadBalancer # <--- THIS IS CRITICAL for public access
  selector: { app: backend }
  ports:
  - port: 80           # What the browser uses (Standard HTTP)
    targetPort: 8080    # What your Go/Python/Node app listens on