apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: shopmicro
spec:
  replicas: 1
  selector:
    matchLabels: { app: ml-service }
  template:
    metadata:
      labels: { app: ml-service }
    spec:
      containers:
      - name: ml-service
        image: timiajiboye/shopmicro-ml:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: shopmicro
spec:
  selector: { app: ml-service }
  ports:
  - port: 5000
    targetPort: 5000