name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # Triggers on every push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Backend
      - name: Build Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shopmicro-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/shopmicro-backend:latest

      # Build and Push ML Service
      - name: Build ML Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shopmicro-ml:latest ./ml-service
          docker push ${{ secrets.DOCKER_USERNAME }}/shopmicro-ml:latest

      # Build and Push Frontend
      - name: Build Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shopmicro-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/shopmicro-frontend:latest